#!/usr/bin/env python

import sys
import os
import upimg
import ConfigParser
from optparse import OptionParser

CONFIG_FILE = "~/.image-uploader"

def process_arguments(default_options):
    # process command line arguments
    program_version = "Images Uploader Utility version %s" % "1.0"
    usage = "usage: %prog [options] images"
    parser = OptionParser(usage = usage, version = program_version)
    parser.add_option(
        "-H", "--help-service",
        action="store", type="string", dest="service_help",
        default="",
        help="display additional help for specified service"
        )
    parser.add_option(
        "-s", "--service", 
        action="store", type="string", dest="service_name",
        default=default_options["service"],
        help="name of service to use"
        )
    parser.add_option(
        "-l", "--list-services",
        action="store_true", dest="list_services",
        help="List all available services."
        )

    (options, args) = parser.parse_args()

    return (options, args, parser)

def main():
    # load config file
    config = ConfigParser.ConfigParser()
    config.read(os.path.expanduser(CONFIG_FILE))
    default_options = { 'global': {
        'service': ''
        } }

    for s in config.sections():
        default_options[s] = {}
        for (k, v) in config.items(s):
            default_options[s][k] = v

    (options, args, parser) = process_arguments(default_options['global'])
    
    services = upimg.list_services()
    service_name = ""

    if options.service_name or options.service_help:
        if options.service_name:
            service_name = options.service_name
        else:
            service_name = options.service_help

        if not service_name in services:
            sys.exit("Unknown upload service: `%s'" % options.service_name)


        default_service_options = {}
        if service_name in default_options:
            default_service_options = default_options[service_name]

        service_options = upimg.get_service_options(service_name)
        group = parser.add_option_group("%s service options" % service_name)
        for op in service_options:
            if op.dest in default_service_options:
                op.default = default_service_options[op.dest]
            group.add_option(op)

    else:
        sys.exit("Unknown upload service: `%s'" % options.service_name)


    # list available services
    if options.list_services:
        print "Available services are:"
        for s in services:
            print 
            print "Name: %s" % s
            print "Description: %s" % upimg.get_service_desc(s)
            pass
        sys.exit(0)

    if options.service_help:
        parser.print_help()
        sys.exit(0)

    if 0 == len(args):
        parser.print_help()
        sys.exit("Specify files to upload")
       
    upimg.upload_files(options, args)

if __name__ == '__main__':
    main()
